### ISSUE TITLE
大神， 两个问题

### ISSUE THREAD

**Issue by Shuliyey** [liyaodong/gugu-node#3]
大神， 我想问下两个问题
* 这个是通过 api call 去和memobird api 沟通， 然后memobird api 会与 咕咕机沟通嘛。我看end point 好像是 http, 不加密会暴露用户信息吧
```
const URL = {
  bind: 'http://open.memobird.cn/home/setuserbind',
  print: 'http://open.memobird.cn/home/printpaper',
```

* 如果是通过 memobird api call 与咕咕机 交流， 那就可以在browser 里工作吧

**Comment by nothingrealhappen** [comment]
你好，

第一个问题： 确实会产生中间人攻击的可能性，对于这个目前没有什么好的办法。因为咕咕鸡的 api 是没有 https 的。

第二个问题：browser 里是可以直接请求咕咕鸡的 api 的，但是 `gugu-node` 因为用到了一些 native only 的包(fs/gm)，所以部分功能在浏览器里面不支持。不过你可以加个 webpack/browserify 在浏览器里试试

很不错的主意 :)

**Comment by Shuliyey** [comment]
谢谢 大神， 我这星期结束前就试试, 咕咕机明天寄到 😄
